---
title: 'Testing plotly with shiny'
output:
  flexdashboard::flex_dashboard:
    orientation: rows   
    vertical_layout: scroll
    css: style.css
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Test

## Row 1 {data-height=1000}

### Test

```{r, test, echo=FALSE}
# Load required libraries
library(shiny)
library(ggplot2)
library(plotly)

ui <- fluidPage(
  selectInput("species_select", "Choose a species:", 
              choices = unique(iris$Species), 
              selected = "setosa"),
  plotlyOutput("scatterPlot"), 
  # tags$head(tags$style("
  #                    #my_tab_box{height:2000px !important;}
  #                    #myplot{height:100px !important;}
  #                    ")),
  tags$head(tags$style("
#scatterPlot {
  height: 85vh;  /* 85% of the viewport height */
}
"))
)

# Define the server logic
server <- function(input, output) {
  
  selected_data <- reactive({
    subset(iris, Species == input$species_select)
  })
  
  output$scatterPlot <- renderPlotly({
    data <- selected_data()
    
    p <- ggplot(data, aes(x = Sepal.Width, y = Sepal.Length)) +
      geom_point(aes(color = Species), size = 3)
    
    ggplotly(p, height = 800)
  })
}

# Run the app
shinyApp(ui = ui, server = server)

```
